---
title: "202A-HW6_4),5)"
author: "Jiayu Wu"
date: "2017/11/15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4)
```{r, echo=FALSE, eval=TRUE, warning=FALSE}
# test functions
myQR <- function(A){
       n <- nrow(A)
       m <- ncol(A)
       R <- A
       Q <- diag(n)
       for (i in 1:(m-1)) {
              X <- matrix(rep(0,n),nrow = n)
              X[i:n] <- R[i:n,i]
              V <- X
              V[i] <- X[i]+norm(X,"F")*sign(X[i])
              U <- V/norm(V,"F")
              R <- R-2*(U%*%t(U)%*%R)
              Q <- Q-2*U%*%t(U)%*%Q
       }
       return(list("Q" = t(Q), "R" = R))
}
mySweep <- function(A, m){
       n <- dim(A)[1]
       for  (k in 1:m) {
              for (j in 1:n) {
                     for (i in 1:n) {
                            if (i != k & j != k) {
                                   A[i,j] <- A[i,j]-A[i,k]*A[k,j]/A[k,k]
                            }
                     }}
              for (i in 1:n) {
                     if (i != k) {
                            A[i,k] <- A[i,k]/A[k,k]
                     }
              }
              for (j in 1:n) {
                     if (j!=k) {
                            A[k,j] <- A[k,j]/A[k,k]
                     }      
              } 
              A[k,k] <- - 1/A[k,k]
       }
       return(A)
       
}
Rcpp::sourceCpp('Sweep.cpp')
myRidge_swp <- function(X, Y, lambda){
       n <- nrow(X)
       p <- ncol(X)
       Z <- cbind(rep(1, n), X, Y) 
       A <- t(Z) %*% Z
       D <- diag(rep(lambda, p+2)) 
       D[1, 1] <- 0
       D[p+2, p+2] <- 0
       A <- A+D
       S <- mySweep(A, p+1)
       beta_ridge <- S[1:(p+1), p+2]
       return(beta_ridge)
}
myRidge_swpc <- function(X, Y, lambda){
       n <- nrow(X)
       p <- ncol(X)
       Z <- cbind(rep(1, n), X, Y) 
       A <- t(Z) %*% Z
       D <- diag(rep(lambda, p+2)) 
       D[1, 1] <- 0
       D[p+2, p+2] <- 0
       A <- A+D
       S <- mySweepC(A, p+1)
       beta_ridge <- S[1:(p+1), p+2]
       return(beta_ridge)
}
myRidge_qr <- function(X, Y, lambda){
       n <- nrow(X)
       p <- ncol(X)
       Z <- cbind(rep(1, n), X, Y)
       D <- diag(rep(sqrt(lambda), p)) 
       D <- cbind(rep(0,p),D,rep(0,p))
       A <- rbind(Z,D)
       R <- myQR(A)$R
       beta_ridge <- solve(R[1:(p+1), 1:(p+1)]) %*% R[1:(p+1),p+2]
       return(beta_ridge)
}
myRidge_qrc <- function(X, Y, lambda){
       n <- nrow(X)
       p <- ncol(X)
       Z <- cbind(rep(1, n), X, Y)
       D <- diag(rep(sqrt(lambda), p)) 
       D <- cbind(rep(0,p),D,rep(0,p))
       A <- rbind(Z,D)
       R <- myQRC(A)$R
       beta_ridge <- solve(R[1:(p+1), 1:(p+1)]) %*% R[1:(p+1),p+2]
       return(beta_ridge)
}
mySpline_swp <- function(x, Y, lambda, p = 100){
       n <- nrow(x)       
       od <- order(x)
       X <- matrix(x[od,],nrow = n)
       x <- x[od,]
       Y <- matrix(Y[od,],nrow = n)
       interval <- (tail(x,1)-head(x,1))/p
       for (i in 1:(p-1)) {
              k <- head(x,1) + (i-1)*interval
              X <- cbind(X, (x>k)*(x-k))
       }
       beta_spline <- myRidge_swp(X, Y, lambda)
       Yhat <- cbind(rep(1, n), X)%*%beta_spline
       output <- list(beta_spline = beta_spline, predicted_y = Yhat)
       return(output)
}
mySpline_swpc <- function(x, Y, lambda, p = 100){
       n <- nrow(x)       
       od <- order(x)
       X <- matrix(x[od,],nrow = n)
       x <- x[od,]
       Y <- matrix(Y[od,],nrow = n)
       interval <- (tail(x,1)-head(x,1))/p
       for (i in 1:(p-1)) {
              k <- head(x,1) + (i-1)*interval
              X <- cbind(X, (x>k)*(x-k))
       }
       beta_spline <- myRidge_swpc(X, Y, lambda)
       Yhat <- cbind(rep(1, n), X)%*%beta_spline
       output <- list(beta_spline = beta_spline, predicted_y = Yhat)
       return(output)
}
mySpline_qr <- function(x, Y, lambda, p = 100){
       n <- nrow(x)       
       od <- order(x)
       X <- matrix(x[od,],nrow = n)
       x <- x[od,]
       Y <- matrix(Y[od,],nrow = n)
       interval <- (tail(x,1)-head(x,1))/p
       for (i in 1:(p-1)) {
              k <- head(x,1) + (i-1)*interval
              X <- cbind(X, (x>k)*(x-k))
       }
       beta_spline <- myRidge_qr(X, Y, lambda)
       Yhat <- cbind(rep(1, n), X)%*%beta_spline
       output <- list(beta_spline = beta_spline, predicted_y = Yhat)
       return(output)
}
mySpline_qrc <- function(x, Y, lambda, p = 100){
       n <- nrow(x)       
       od <- order(x)
       X <- matrix(x[od,],nrow = n)
       x <- x[od,]
       Y <- matrix(Y[od,],nrow = n)
       interval <- (tail(x,1)-head(x,1))/p
       for (i in 1:(p-1)) {
              k <- head(x,1) + (i-1)*interval
              X <- cbind(X, (x>k)*(x-k))
       }
       beta_spline <- myRidge_qrc(X, Y, lambda)
       Yhat <- cbind(rep(1, n), X)%*%beta_spline
       output <- list(beta_spline = beta_spline, predicted_y = Yhat)
       return(output)
}

# test data
n = 20
p = 100
sigma = 0.1
lambda = 1
set.seed(7)
x = runif(n)
x = sort(x)
x = matrix(x, nrow=n)
Y = x^2 + rnorm(n)*sigma
# sweep
t1 <- system.time(mySpline_swp(x,Y,lambda,p))
# sweepC
t2 <- system.time(mySpline_swpc(x,Y,lambda,p))
# qr
t3 <- system.time(mySpline_qr(x,Y,lambda,p))
# qrC
t4 <- system.time(mySpline_qrc(x,Y,lambda,p))
# contrast time
t<-rbind(t1,t2,t3,t4)[,1:3]
rownames(t) <- c("sweep","sweep_c","qr","qr_c")
library(knitr)
kable(t,align = "c",caption = "Time for Spline Regression with Competing Methods (n=20, p=100)")
```

C is significantly faster than R. QR algorithm is a lot faster than Sweep algorithm by comparing qr and sweep, however solve() function in R is too time-consuming, so both qr and qr_c are slower than sweep_c. 

## 5)
```{r, echo=FALSE, eval=T, warning=FALSE}
Rcpp::sourceCpp('Sweep.cpp')
myRidge <- function(X, Y, lambda){
       n <- nrow(X)
       p <- ncol(X)
       Z <- cbind(rep(1, n), X, Y) 
       A <- t(Z) %*% Z
       D <- diag(rep(lambda, p+2)) 
       D[1, 1] <- 0
       D[p+2, p+2] <- 0
       A <- A+D
       S <- mySweepC(A, p+1)
       beta_ridge <- S[1:(p+1), p+2]
       return(beta_ridge)
}
mySpline <- function(x, Y, lambda, p = 100){
       n <- nrow(x)       
       od <- order(x)
       X <- matrix(x[od,],nrow = n)
       x <- x[od,]
       Y <- matrix(Y[od,],nrow = n)
       interval <- (tail(x,1)-head(x,1))/p
       for (i in 1:(p-1)) {
              k <- head(x,1) + (i-1)*interval
              X <- cbind(X, (x>k)*(x-k))
       }
       beta_spline <- myRidge(X, Y, lambda)
       Yhat <- cbind(rep(1, n), X)%*%beta_spline
       output <- list(beta_spline = beta_spline, predicted_y = Yhat)
       return(output)
}
# training data
n = 20
p = 100
sigma = 0.1
set.seed(7)
x = runif(n)
x = sort(x)
x = matrix(x, nrow=n)
Y = x^2 + rnorm(n)*sigma
# testing data
n = 20
p = 100
sigma = 0.1
set.seed(1)
xt = runif(n)
xt = sort(xt)
xt = matrix(xt, nrow=n)
Yt = xt^2 + rnorm(n)*sigma
# set lambdas
lambda <- seq(0.002,0.262,0.005)
# ridge regression
xi <- cbind(rep(1,n),x)
xti <- cbind(rep(1,n),xt)
Yhats_r <- apply(t(lambda),2,function(lambda){
       xi%*%myRidge(x,Y,lambda)})
train_er <- apply(t(lambda),2,function(lambda){
       sum((Y-xi%*%myRidge(x,Y,lambda))^2)})
test_er <- apply(t(lambda),2,function(lambda){
       sum((Yt-xti%*%myRidge(x,Y,lambda))^2)})
# spline regression with p=100
Yhats <- apply(t(lambda),2,function(lambda){mySpline(x,Y,lambda,p)$predicted_y})
train_err <- apply(t(lambda),2,function(lambda){sum((Y-mySpline(x,Y,lambda,p)$predicted_y)^2)})
test_err <-apply(t(lambda),2,function(lambda){
       beta <- mySpline(x,Y,lambda,p)$beta_spline
       Xt <- xt
       xt <-sort(xt)
       interval <- (tail(xt,1)-head(xt,1))/p
       for (i in 1:(p-1)) {
              k <- head(xt,1) + (i-1)*interval
              Xt <- cbind(Xt, (xt>k)*(xt-k))
       }
       Yhat <- cbind(rep(1, n), Xt) %*% beta
       sum((Yt-Yhat)^2)})
# data for plotting
dfr <- data.frame(x=rep(x,length(lambda)),
                 y=as.numeric(Yhats_r),lambda=rep(lambda, each=n),
                 x_point=rep(x,length(lambda)),
                 y_point=rep(Y[order(x),],length(lambda)))
er <- data.frame(lambda=rep(lambda, 2),
                  type=rep(c("testing","training"),each=length(lambda)),
                  error=c(test_er,train_er))
# x_simulate <- runif(n*length(lambda))
df <- data.frame(x=rep(sort(x),length(lambda)),
                 y=as.numeric(Yhats),lambda=rep(lambda, each=n),
                 x_point=rep(sort(x),length(lambda)),
                 y_point=rep(Y[order(x),],length(lambda)))
err <- data.frame(lambda=rep(lambda, 2),
                  type=rep(c("testing","training"),each=length(lambda)),
                  error=c(test_err,train_err))
# plot
library(ggplot2)
p_fitr <- ggplot(dfr)+geom_line(aes(x,y,group=lambda, color=lambda))
p_fitr <- p_fitr+geom_point(aes(x_point,y_point))
p_fitr <- p_fitr+theme_classic()+ggtitle("Fitted Ridge Regression Curves with Observed Data")
p_fitr
p_fit <- ggplot(df)+geom_line(aes(x,y,group=lambda, color=lambda))
p_fit <- p_fit+geom_point(aes(x_point,y_point)) #+geom_line(aes(xtrue,ytrue),color="red")
p_fit <- p_fit+theme_classic()+ggtitle("Fitted Spline Regression Curves with Observed Data")
p_fit
p_er <- ggplot(er,aes(x=lambda,y=error,color=type))+geom_line()
p_er <- p_er+theme_classic()+ggtitle("Training and Testing Errors for Ridge Regression")
p_er
p_err <- ggplot(err,aes(x=lambda,y=error,color=type))+geom_line()
p_err <- p_err+theme_classic()+ggtitle("Training and Testing Errors for Spline Regression")
p_err
```
